Android feature
xlui/FlippedClassroom pull request #11
Opened 2018-01-24 04:21 UTC by TotoroXkf

Android端完成了
- 注册的逻辑
- 登录的逻辑
- 区分学生和老师，保存token到本地

2018-01-24 05:43 UTC, xlui requested changes
类的注释、方法注释

2018-01-26 01:12 UTC, xlui approved these changes

2018-01-26 01:13 UTC, xlui commented
把自己 @TotoroXkf 和 @3441242166  的提交内容分别概括一下，作为合并 commit 后的 commit message

2018-01-26 01:48 UTC, TotoroXkf commented
Android端完成了
- 注册的逻辑
- 登录的逻辑
- 区分学生和老师，保存token到本地 
</br>

 @3441242166 完成了从本地读取token和身份信息的逻辑
@TotoroXkf 完成了注册，登录的ui和逻辑，以及架构的搭建

2018-01-26 02:01 UTC, merged